apiVersion: v1
kind: Service
metadata:
  name: gpt-oss-20b-vllm-lb
  namespace: gpt-oss-20b-benchmark
spec:
  type: ClusterIP
  selector:
    serving.kserve.io/inferenceservice: gpt-oss-20b-vllm
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
